[project]
name = "25-01-2025-finetuning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bitsandbytes>=0.45.5",
    "colorama>=0.4.6",
    "datasets>=3.6.0",
    "docling>=2.15.1",
    "litellm>=1.68.0",
    "pandas>=2.2.3",
    "peft>=0.15.2",
    "pydantic>=2.11.4",
    "trl>=0.12.2",
]
